# -*- mode: ruby -*-
# vi: set ft=ruby :

# Gerardo Ocampos 2021

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_version = "1809.01"
  config.vm.box_check_update = false

  config.vm.define 'node1' do |master|
    master.vm.hostname = "node1.ocampoge.com"
    master.vm.network "private_network", ip: "192.168.33.51"
    master.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
    end
    master.vm.provision "shell", inline: <<-SHELL
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd
      yum update -y
    SHELL
  end

  config.vm.define 'node2' do |master|
    master.vm.hostname = "node2.ocampoge.com"
    master.vm.network "private_network", ip: "192.168.33.52"
    master.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
    end
    master.vm.provision "shell", inline: <<-SHELL
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd
      yum update -y
    SHELL
  end

end
