# -*- mode: ruby -*-
# vi: set ft=ruby :

# Gerardo Ocampos 2021

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_version = "1809.01"
  config.vm.box_check_update = false

  config.vm.define 'gitea' do |master|
    master.vm.hostname = "gitea.ocampoge.com"
    master.vm.network "private_network", ip: "192.168.33.53"
    master.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
    master.vm.provision "file", source: "../../install/gitea/init.sh", destination: "init.sh"
    master.vm.provision "file", source: "../../install/gitea/docker-compose.yml", destination: "docker-compose.yml"
    master.vm.provision "shell", inline: <<-SHELL
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd
      chmod +x init.sh
      ./init.sh
      docker-compose up -d
    SHELL
  end
end

